### ISSUE TITLE
Rubocop Cleanup

### ISSUE THREAD

**Issue by karcaw** [alno/chef-motion#2]
There are quite a lot of Rubocop issues with this cookbook, How do you feel about me cleaning up the issues?
Most of them are syntax changes.

```
--> rubocop -fo
53  Style/StringLiterals
3   Style/HashSyntax
2   Style/EmptyLinesAroundBlockBody
1   Lint/DeprecatedClassMethods
1   Metrics/LineLength
1   Style/TrailingBlankLines
--
61  Total
```

**Comment by karcaw** [comment]
The only needed rubocop config it seems is needed is:
Metrics/LineLength:
  Max: 132

The other issues are easily fixed.

**Comment by alno** [comment]
Thanks, merged it.
